### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds_lots_extension#2]
From Jachym

> 1) I noticed a typo at:
> 
> http://standard.open-contracting.org/1.1-dev/en/extensions/lots/ 
> 
> lotGroups -	Tender - ere the buyer reserves the right to combine lots, or wishes to specify the total value for a group of lots, a lot group is used to capture this information.	array
>
> 2) Also, is it intentional that in the table, the column which contains "sections" is labeled "definition"? 
> 
> 3) You also use relatedLot, not relatedLots quite frequently on the page.
> 

Updates to make

**Comment by jpmckinney** [comment]
Seems closed in referenced commit. The column headers for those tables may be confusing, but they are shared across all extensions. Can open an issue on `standard` if we want to change them.
