### ISSUE TITLE
Json example validation

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds_lots_extension#4]
The current json example file doesn't validate against the schema (1.0), because the attribute uri is missing in the meta-data.
We need to add something like: 
`"uri":` "https://github.com/open-contracting/ocds_lots_extension/blob/master/examples/lots.json"

**Comment by timgdavies** [comment]
Good spot - do you want to submit a pull-request to fix that?

**Comment by yolile** [comment]
Submitted the pull request: #5
